# Generated by Django 5.1.1 on 2025-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coupon_is_active_shippingaddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed Transaction'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
