- name: 'Install system dependencies'
  become: true
  apt: 
    update_cache: true
    name: 
      - gcc
      - libpq-dev
      - pip
      - virtualenv
      - gunicorn
    clean: true
- name: 'repostory file using state'
  file: 
    state: 'absent'
    path: '/var/lib/apt/lists/*'
# - name: 'cloning github repository'
#   become: true
#   git:
#     accept_hostkey: true
#     force: true
#     repo: 'git@github.com:MBarre28/MB-ecommerce.git'
#     dest: '{{working_directory}}'
#     key_file: '/home/worker-node/.ssh/id_ed25519'
- name: 'Create media directory with proper permissions'
  become: true
  file:
    path: '{{working_directory}}/media'
    state: 'directory'
    mode: '755'
- name: 'Install Python dependencies'
  become: true
  ansible.builtin.pip:
    requirements: '{{working_directory}}/requirements.txt'
    virtualenv: '/opt/ecommerce/venv'
    virtualenv_python: 'python3'
- name: 'Collect static files'
  become: true
  ansible.builtin.shell: |
    source /opt/ecommerce/venv/bin/activate 
    cd '{{working_directory}}/'
    python manage.py collectstatic --noinput
  args:
    executable: /bin/bash   
- name: 'gunicorn setup file'
  become: true
  ansible.builtin.template: 
    src: service.j2
    dest: /etc/systemd/system/ecommerce.service
    owner: root
    group: root
    mode: '0644'
- name: 'Reloading systemd & restarting servers'
  become: true
  ansible.builtin.systemd: 
    daemon_reload: yes
    name: ecommerce.service
    state: restarted
- name: 'setting up the environment vars'
  become: true
  ansible.builtin.template: 
    src: 'env.j2'
    dest: '{{working_directory}}/.env'
    owner: 'root'
    group: 'root'
    mode: '0644'
- name: 'VM migration'
  become: true
  ansible.builtin.shell: |
    source /opt/ecommerce/venv/bin/activate 
    cd '{{working_directory}}/'
    python manage.py migrate
  args:
    executable: /bin/bash
- name: 'creating a superuser'
  become: true
  ansible.builtin.shell: |
    source /opt/ecommerce/venv/bin/activate 
    cd '{{working_directory}}/'
    python manage.py createsuperuser --noinput
  args:
    executable: /bin/bash
  environment: 
    DJANGO_SUPERUSER_USERNAME: '{{superuser_username}}'
    DJANGO_SUPERUSER_EMAIL: '{{superuser_email}}'
    DJANGO_SUPERUSER_PASSWORD: '{{superuser_password}}'
  register: 'result'
  changed_when: "'already taken' not in result.stderr.lower()"
  failed_when: false
- name: 'Debug superuser'
  ansible.builtin.debug: 
    # msg: '{{result.stdout}}'
    var: result
