---
# vars file for roles/webservers

working_directory: /etc/ecommerce
venv: /opt/ecommerce/venv/bin/gunicorn
pythondontwritebytecode: 1
pythonunbuffered: 1
debug: 1
description: MB ecommerce site
exec_start: projectecommerce.wsgi:application --bind 0.0.0.0:8000
db_user: 'db-node'
db_password: 'database-node28'
db: 'db-node'
superuser_username: 'mb-ecome21'
superuser_email: 'mbcom12@gmail.comea'
superuser_password: 'ecompasstest!2828*12'
