---

- name: Muhammads playbook for updating VMs and packages
  hosts: all
  roles:
    - update

- name: Muhammads Playbook for deploying webservers
  hosts: webservers
  roles:
    - webservers

- name: database node collection
  hosts: db
  roles:
    - database
